### PR TITLE
Updated wrong ids in constants.py

### PR DESCRIPTION
**Pull request by vivax3794**
the ids were not the ones for the main server meaning the bot would not work "out of the box" on the main server.

### CODE REVIEW

**Comment by vivax3794** [comment]
dont merge yet, looks like the emojies are also wrong, so let's fix that to

**Comment by gustavwilliam** [comment]
Thanks for the PR @vivax3794. Is it ready to be merged now?

**Comment by vivax3794** [comment]
> Thanks for the PR @vivax3794. Is it ready to be merged now?

it is

**Review by codephile1221 — APPROVED** [review]
LGTM! I like your coding style. Keep it up :+1:

**Review by gustavwilliam — APPROVED** [review]
LGTM

**Pull request merged**
