### PR TITLE
Add Docker setup

### PR DESCRIPTION
**Pull request by Akarys42**
This PR adds the following:
* A Dockerfile defining the bot container
* A Docker Compose setup to facilitate the launch of the container
* A workflow to push the container to GHCR
* Some small changes to fix the Pipfile

### CODE REVIEW

**Review by Shivansh-007 — APPROVED** [review]
Thanks! Looks Good To Me!

**Comment by gustavwilliam** [comment]
Has anyone tested this and made sure it works?

**Comment by ReneganRonin** [comment]
i will test this.

**Review by ReneganRonin — COMMENTED** [review]
Confirming that it worked :D

**Comment by gustavwilliam** [comment]
Fantastic, thanks! I’ll merge.

**Pull request merged**
