### PR TITLE
Updated help command

### PR DESCRIPTION
**Pull request by ChiliPy**
In this PR, im adding a custom help command ~~so we don't have to continue to use the shitty default one~~ that replaces the current one.

### CODE REVIEW

**Comment by Shivansh-007** [comment]
Better git commit messages please.

**Comment by ChiliPy** [comment]
> Better git commit messages please.
"In this PR, im adding a custom help command so we don't have to continue to use the shitty default one." Perfectly describes what I'm doing. If you want to you can make the pr yourself so it's perfect or whatever. The branch is chilipy/main

**Comment by ChiliPy** [comment]
Also if you are going to tell me to do something better at least give me an example of how you want it. Because atm Idk what you even want changed.

**Comment by ChiliPy** [comment]
vester was _very_ helpful in dms and didn't give me a clear answer, so the PR is being closed. Have fun with your shitty default one.

**Pull request closed without merging**
