### PR TITLE
fixed eval bug when language is given in codeblock

### LINKED ISSUE #74: Eval command bug
When you do
!e py
```
a
```
Here the language is specified outside the code block
It gives error: https://discord.com/channels/789192517375623228/793570459945926717/800007399778811954

but when you do
!e
```py
a
```
Here the language is specified inside the code block
It does not give error: https://discord.com/channels/789192517375623228/793570459945926717/800007441349345281

### PR DESCRIPTION
**Pull request by vivax3794**
Fixes #74

### CODE REVIEW

**Comment by vivax3794** [comment]
there is still a variation of the bug if the first line of the code is `py`/`python` or whatever the lang is, but I find it unlikely this will happen anyway.

**Comment by vivax3794** [comment]
wait never mind, still broken 
image

**Comment by vivax3794** [comment]
this is not perfect BUT
I have narrowed the amount of situations the bug will happen (when looking at the first line) from infinity to 1

**Comment by vivax3794** [comment]
the bug still triggers if the first line of the code matches the lang exactly for, or when the lang in the codeblock and the one outside are different.

**Comment by vivax3794** [comment]
okay I just thought of something much simpler and it works for all the situations

**Review by Shivansh-007 — APPROVED** [review]
Looks Good.

**Comment by Shivansh-007** [comment]
Can someone quickly have a look at this so that we can merge this?

**Review by RandomDev26 — APPROVED** [review]
LGTM!

**Pull request merged**
