### PR TITLE
Creating the basic directory structure for the bot

### PR DESCRIPTION
**Pull request by ReneganRonin**
I created the directory structure for the bot:
```
.
├── bot
│   ├── cogs
│   │   └── __init__.py
│   ├── __init__.py
│   └── __main__.py
├── LICENSE
├── Pipfile
├── Pipfile.lock
└── README.md
```
it looks like this for now. feel free to comment and discuss with me :smiley:

### CODE REVIEW

**Comment by ReneganRonin** [comment]
My idea is:

> Once we are done with the basic structure, we can then create another branch `develop` where we can test features by creating branches based off of `develop` for the bot before merging such features to `develop`. Further testing may promote such features from `develop` to `main` and then we select which features to implement for the bot in the  `release` branch.

**Comment by Shivansh-007** [comment]
Cool! The PR looks good to me!

**Comment by ReneganRonin** [comment]
# My Idea is too complex...
Based on @gustavwilliam 's suggestion, my idea is rather complex since the bot is still at its infancy. So here is the updated workflow according to @gustavwilliam :
### Steps
1. Evaluate what features we want
2. Create bot core and fix dependency management and similar
3. Implement features

### Comments on workflow:
1. I agree on the workflow.
2. I suggest we create two branches - `core` and `develop`:
  - `core` branch _is_ the bot's core so if anything is messed up, it stays there.
  - `develop` is where we test the new features. We create this features by branching off from the `develop` branch. The branches should be named after the feature (e.g. `feature/ci`) and then PR to develop for further testing. These will prevent mishaps if something goes wrong from the feature branch.
3. Alrighty! Let's go!!!

Feel free to comment here and discuss.

**Comment by gustavwilliam** [comment]
@ReneganRonin maybe this would work even better as a discussion issue?

**Comment by ReneganRonin** [comment]
@gustavwilliam alrighty

**Comment by Xithrius** [comment]
If we need a database I suggest using Postgres within Docker.

**Comment by ReneganRonin** [comment]
@Xithrius feel free to open discussion in https://github.com/gurkult/gurkbot/issues/7#issue-770758569

**Comment by mudkipdev** [comment]
yeah i dont know why we need this, we should just add things as we need them, plus you forgot a utils folder

**Comment by gustavwilliam** [comment]
> yeah i dont know why we need this, we should just add things as we need them, plus you forgot a utils folder

@mudkipdev these are some great contributions. The fact that @ReneganRonin took the time to work on the fundamental folder structure for the project is really valuable. That's something we need to have in a structured and well-built application. The issue with this PR wasn't the contents, but rather the fact that it would fit better as an issue.

Also, try to keep a positive tone. That message seemed more like your were trying to point out every flaw in the PR. We prosper as a community only when we are encouraging and inclusive.

**Comment by mudkipdev** [comment]
> Also, try to keep a positive tone. That message seemed more like your were trying to point out every flaw in the PR. We prosper as a community only when we are encouraging and inclusive.

Sorry if it sounded that way, I was just trying to give a suggestion. I also agree that this should fit better as an issue or a discussion rather than a pull request.

**Pull request closed without merging**
