### PR TITLE
Workflows and dependencies

### PR DESCRIPTION
**Pull request by Xithrius**
Greetings, humans.

This PR is meant to add the base virtual environments for development of the bot and a singular workflow.

`Pipfile` and `Pipfile.lock` are the two base files that will most likely be added upon in the future, while the added workflow takes advantage of the development packages to lint pushes and PRs.

### CODE REVIEW

**Comment by ReneganRonin** [comment]
@gustavwilliam I do not think that we should merge this PR. I have a bad feeling that Xithy the bot might be infected with malicious code.


jokes aside, what do u think about this @fisher60 ? I mean it is Xithy so I trust what he always PR.

**Comment by Xithrius** [comment]
> Oh lol we have the same Pipfile content as before.

I don't see any `Pipfile` in the main branch. I'm not sure what you mean by this.

**Comment by ReneganRonin** [comment]
@Xithrius dont mind me xD i am just sharing what i did before this

**Comment by Shivansh-007** [comment]
Well not sure but do we need precommit config? And also add pre-commit to the workflow.

**Review by gustavwilliam — COMMENTED** [review]
Nice! I don’t feel confident enough in this area to approve and merge, but it looks good to me.

The only think I’m unsure about is is we should have that many exceptions in flake8. Do you think they’re good to have, or should we start off with a tighter config and expand as needed? I know @fisher60 has a basic config that’s not too extensive.

**Comment by Vyvy-vi** [comment]
imho, currently ignoring doc-strings inside flake8 might be better since we might not be documenting the bot much as of now

**Comment by gustavwilliam** [comment]
I honestly think we should strive to have docstrings in most places. Just a quick one-liner is great for making sure that people know what it does. I like docstrings.

**Comment by vivax3794** [comment]
can we get this merged so I can start work on the core code?

**Comment by Xithrius** [comment]
> The only think I’m unsure about is is we should have that many exceptions in flake8.

We actually do need this many exceptions so we can work properly. This PR is done for now, I've added the `.pre-commit-config.yaml` file as well.

**Pull request merged**
