### PR TITLE
Bump pyyaml from 5.3.1 to 5.4

### PR DESCRIPTION
**Pull request by Shivansh-007**
> Bumps [pyyaml](https://github.com/yaml/pyyaml) from 5.3.1 to 5.4.
> - [Release notes](https://github.com/yaml/pyyaml/releases)
> - [Changelog](https://github.com/yaml/pyyaml/blob/master/CHANGES)
> - [Commits](https://github.com/yaml/pyyaml/compare/5.3.1...5.4)
> 
> Signed-off-by: dependabot[bot] <support@github.com>

https://github.com/Shivansh-007/gurkbot/security/dependabot/Pipfile/PyYAML/open

### CODE REVIEW

**Comment by gustavwilliam** [comment]
Have you tested this locally?

**Comment by Shivansh-007** [comment]
Yes, this has been tested locally @gustavwilliam

**Comment by gustavwilliam** [comment]
Alright, perfect. I'd love to have a second person test this before merging. Currently, I'm not able to do that.

**Review by RandomDev26 — APPROVED** [review]
Tested it out, everything seems to work!

**Pull request merged**
