### PR TITLE
added user's github profile link

### PR DESCRIPTION
**Pull request by ShakyaMajumdar**
image

(PS: PRing on behalf of Arnav if things go wrong blame him ok)

### CODE REVIEW

**Review by RandomDev26 — APPROVED** [review]
LGTM

**Review by Arnav-2004 — APPROVED** [review]
LGTM!

**Comment by gustavwilliam** [comment]
Did you test this?

**Comment by ShakyaMajumdar** [comment]
@Arnav-2004 ^

**Comment by Arnav-2004** [comment]
> Did you test this?

Yes the screenshot is of the test.

**Comment by Arnav-2004** [comment]
Wait it doesn't work if the user is not found.

**Comment by Arnav-2004** [comment]
> Wait it doesn't work if the user is not found.

@gustavwilliam it should work now
image
Sorry for not testing if user didn't exist at first.

**Comment by gustavwilliam** [comment]
Okay. I'd like to see two approving reviews that have *tested* it.

**Review by vivax3794 — APPROVED** [review]
Tested and looks good

**Pull request merged**
